### ISSUE TITLE
Teku update not compatible

### ISSUE THREAD

**Issue by InoMurko** [dappnode/DAppNodePackage-teku-generic#17]
![image](https://github.com/user-attachments/assets/5e6f0dbf-8162-4dd3-b4df-7a2983131108)

**Comment by Marketen** [comment]
Same issue as https://github.com/dappnode/DAppNodePackage-nethermind-generic/issues/11#issuecomment-2527452839. You will need to uninstall mevboost & your consensus client, then update nethermind and reinstall CC & mevboost.

**Comment by InoMurko** [comment]
> Same issue as https://github.com/dappnode/DAppNodePackage-nethermind-generic/issues/11#issuecomment-2527452839. You will need to uninstall mevboost & your consensus client, then update nethermind and reinstall CC & mevboost.

Oh wow this is incredibly intrusive. What is the origin of the issue upstream? Is there a reference you could share pls?
